import Head from "next/head";
import Hero from "widgets/home/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecology - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </>
  );
}
